# Vendored from tradingagents/agents/utils/agent_states.py + tradingagents/graph/propagation.py (messages channel removed).
"""State contract: parent TypedDicts minus the LangGraph messages channel.

Field names are the parent's, verbatim — checkpoints and reports written by
either implementation stay mutually readable. ``total=False`` because the
state accretes fields as the pipeline progresses.
"""

from typing import Annotated, TypedDict

from tradingagents.dataflows.utils import safe_ticker_component

__all__ = [
    "InvestDebateState",
    "RiskDebateState",
    "AgentState",
    "create_initial_state",
    "normalize_ticker",
    "safe_ticker_component",
]


# Researcher team state
class InvestDebateState(TypedDict, total=False):
    bull_history: Annotated[str, "Bullish Conversation history"]
    bear_history: Annotated[str, "Bearish Conversation history"]
    history: Annotated[str, "Conversation history"]
    current_response: Annotated[str, "Latest response"]
    judge_decision: Annotated[str, "Final judge decision"]
    count: Annotated[int, "Length of the current conversation"]


# Risk management team state
class RiskDebateState(TypedDict, total=False):
    aggressive_history: Annotated[str, "Aggressive Agent's Conversation history"]
    conservative_history: Annotated[str, "Conservative Agent's Conversation history"]
    neutral_history: Annotated[str, "Neutral Agent's Conversation history"]
    history: Annotated[str, "Conversation history"]
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[str, "Latest response by the aggressive analyst"]
    current_conservative_response: Annotated[str, "Latest response by the conservative analyst"]
    current_neutral_response: Annotated[str, "Latest response by the neutral analyst"]
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]


class AgentState(TypedDict, total=False):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[str, "Report from the News Researcher of current world affairs"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[
        str,
        "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)",
    ]


def create_initial_state(
    company_name: str, trade_date: str, past_context: str = ""
) -> AgentState:
    """Create the initial pipeline state (parity with the parent Propagator)."""
    return AgentState(
        company_of_interest=company_name,
        trade_date=str(trade_date),
        past_context=past_context,
        investment_debate_state=InvestDebateState(
            bull_history="",
            bear_history="",
            history="",
            current_response="",
            judge_decision="",
            count=0,
        ),
        risk_debate_state=RiskDebateState(
            aggressive_history="",
            conservative_history="",
            neutral_history="",
            history="",
            latest_speaker="",
            current_aggressive_response="",
            current_conservative_response="",
            current_neutral_response="",
            judge_decision="",
            count=0,
        ),
        market_report="",
        fundamentals_report="",
        sentiment_report="",
        news_report="",
    )


def normalize_ticker(t: str) -> str:
    """Canonical ticker form for prompts, paths, and checkpoint thread ids."""
    return t.strip().upper()
